version: '2'
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go-fiber-example
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - postgres
    restart: unless-stopped
